apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    app: open-webui
  name: open-webui
  namespace: __NAMESPACE__
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:ollama
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui
      - name: deepseek-r1--1-5b
        image: ghcr.io/open-webui/open-webui:ollama
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
          limits:
            memory: "8Gi"
            cpu: "8"
        command: ["/bin/sh", "-c", "cd /app/backend/data && while true ; do ollama run deepseek-r1:1.5b ; sleep 1 ; done"]
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui
      - name: qwen--0-5b
        image: ghcr.io/open-webui/open-webui:ollama
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "6"
        command: ["/bin/sh", "-c", "cd /app/backend/data && while true ; do ollama run qwen:0.5b ; sleep 1 ; done"]
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: open-webui
        persistentVolumeClaim:
          claimName: open-webui

