apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    app: open-webui
  name: open-webui
  namespace: __NAMESPACE__
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:ollama
        env:
          - name: OPENAI_API_KEY
            value: '__OPENAI_API_KEY__'
          - name: USE_OLLAMA_DOCKER
            value: "True"
          - name: OLLAMA_MODELS
            value: /app/backend/data/models
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui
        resources:
          requests:
            memory: "6Gi"
            cpu: "6"
          limits:
            memory: "12Gi"
            cpu: "12"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: open-webui
        persistentVolumeClaim:
          claimName: open-webui

